### ISSUE TITLE
futures 3.1.2 breaks the world :-)

### ISSUE THREAD

**Issue by kapilt** [agronholm/pythonfutures#83]
If you have a python 2/3 compatible package that uses third party dependencies that use concurrent.futures then using 3.1.2 causes an error on install for python 3.  Thats unfortunate as its a common dependency for things that are 2/3 compatible. I have a half-dozen third party libraries in venv that depend on futures.

```
Collecting futures==3.1.2 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/4a/f4/418e844d868e34638486732417fb82b05031910059d88b86aaea9c70f699/futures-3.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}
    
```

**Comment by alfpark** [comment]
There is no release or [changelog](https://github.com/agronholm/pythonfutures/blob/master/CHANGES.rst) associated with 3.1.2, nor is there a 3.1.2 tag in the repo. It appears that 3.2.0 was the [prior latest version](https://pypi.org/project/futures/#history). For reasons that I'm unaware of, projects that aren't pinning this package to a specific version are installing 3.1.2 instead of the semantic latest version, 3.2.0 (which hasn't changed since Nov-2017).

**Comment by reaCodes** [comment]
I encountered the same trouble😐

---
![image](https://user-images.githubusercontent.com/13817254/40029659-50b6ed6a-5818-11e8-9c25-47fff031ab75.png)

**Comment by cybergrind** [comment]
@agronholm hey, this definitely wasn't just `patch` version that is safe to upgrade. 

Is `exit(1)` absolutely necessary? It seems working for python3 installations, at least it doesn't break anything explicitly.

**Comment by Kyria** [comment]
After checking all my CI's, it looks like none of the py3 I have ever used 3.2.0, but always used 3.1.1, because this line have been added to 3.2.0 in the setup.py
```
      python_requires='>=2.6, <3',
``` 
While the 3.1.x version doesn't have it (so py3 is able to download that version only)

Can you fix either case: 
- either add `python_requires='>=2.6, <3',` in 3.1.2, since it's better than an `exit(1)` (which makes no sense, since the py version was allowed to download it with pip) or remove the exit(0) while leaving the warning
- remove the python_requires on the 3.2.x branch

Anyway, all of us, we should fix our setup.py ;), and thanks for your work !

Thanks !

**Comment by agronholm** [comment]
I've removed the 3.1.2 release, as it was unreasonably inconveniencing end users. That said, I think it got the message across.

**Comment by takluyver** [comment]
Rather than failing out of the installation on Python 3, why not make the package empty when it's installed on Python 3, so installation will 'succeed' but won't shadow the standard library? Something like this:

```python
packages=['concurrent', 'concurrent.futures'] if sys.version_info == 2 else [],
```

**Comment by mpacer** [comment]
@takluyver: Oh wow, I hadn't thought of that! That's a totally great idea since it avoids breaking people's installs!

@agronholm: I apologise for leading you down a path that lead to user pain when this was a possibility!  Installing nothing is definitely the best approach.

**Comment by agronholm** [comment]
@takluyver Pip cannot install `futures` in a way that will shadow the standard library. That is why this problem has confused me. Try creating a new virtualenv and installing `futures`. Then do `import concurrent` and `print(concurrent.__file__)`. You'll see that it points to the standard library and not this backport. That begs the question: why is this workaround needed in the first place?

**Comment by agronholm** [comment]
I'd be interested in hearing how `futures` can be installed in a way that will override the stdlib import.

**Comment by takluyver** [comment]
I fiddled around for a couple of minutes and couldn't make it happen, but we've definitely had problems of this kind before. It doesn't even have to be how `futures` is installed, IIRC; installing something completely unrelated can create a `.pth` file which can change the order of imports.

**Comment by mpacer** [comment]
I wasn't able to reproduce this anymore — not sure what was going on before (`pip > 10`, and definitely installed 3.1.1 which broke `pytest` by monkey-patching `__get_result` to use python2 syntax). Not sure though, so unless it comes up again, I'll stop pushing on this. Thanks for your patience!
